#!/bin/sh

# this script generates developer documentation from all README.md files in the git repositories cloned below

TMPDIR=$(mktemp -d)
OUTPUT=developerdocs.html

pushd $TMPDIR

# get all arden2bytecode repos
git clone https://github.com/hflicka/example-mlms.git
git clone https://github.com/hflicka/arden2bytecode-homepage.git
git clone https://github.com/hflicka/ardensyntax-eclipse-plugin.git
git clone https://github.com/hflicka/arden2bytecode.git

# clone and compile markdown parser
git clone https://github.com/vmg/sundown.git

cd sundown
make
cd ..

popd

# concatenate all markdown files and add headings
find $TMPDIR -name README.md -and -not -name sundown -exec echo \<hr\>\<h1\>NAME:{}\</h1\> \; -exec ./sundown/sundown {} \; | sed "s|NAME:$TMPDIR/||" > $OUTPUT

rm -rf $TMPDIR

echo "done. docs are in $OUTPUT"
